### ISSUE TITLE
IAVL Dependency Inversion Refactor - create nodeDB interface for immutable and mutable trees

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/iavl#15]
**Background**

Please refer to [#14](https://github.com/osmosis-labs/iavl/issues/14) for more background information.

This task is specific to creating an interface for `nodeDB` and refactoring mutable and immutable tree to depend on the new abstraction instead of the concrete nodeDB struct.

**Acceptance Criteria**
- [ ] An interface for nodeDB is created
- [ ] mutable tree is refactored to depend on the new nodeDB interface
- [ ] immutable tree is refactored to depend on the new nodeDB interface
- [ ] mock nodedb is created and existing unit tests are refactored to use the mock
- [ ] existing unit tests are refactore
- [ ] additional unit tests are added where needed
- [ ] all unit tests pass

**Comment by rohanspersonalgit** [comment]
Hi, looking to contribute! working off my fork here, will appreciate any feedback on my progress as I get my PR ready.
https://github.com/RohansPersonalGit/iavl

**Comment by p0mvn** [comment]
thanks, @RohansPersonalGit . I saw a draft PR and will get back to you there soon

**Comment by p0mvn** [comment]
Given how risky changes on IAVL are. I think that this refactor is not worth the effort so I'm going to close this. Please let me know if any concerns
