### ISSUE TITLE
Refactor common `Node` interface from `Node` and `FastNode` structs

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/iavl#25]
**Background**

Please refer to [#14](https://github.com/osmosis-labs/iavl/issues/14) for more background information.

This task is specific to creating an interface for `Node` and refactoring the dependents to depend on the new abstraction instead of the concrete `Node` or `FastNode` struct.

This issue is blocking and must be done before: https://github.com/osmosis-labs/iavl/issues/24

**Acceptance Criteria**
- [ ] Rename `Node` struct to `TreeNode`
- [ ] Determine methods that can be shared between `TreeNode` and `FastNode`
- [ ] Create `Node` interface with the mentioned-above methods
- [ ] Refactor all dependents of the `TreeNode` to depend on the `Node` interface instead
- [ ] Refactor all dependents of the `FastNode` to depend on the `Node` interface instead
- [ ] mock `Node` is created and existing unit tests are refactored to use the mock
- [ ] additional unit tests are added where needed
- [ ] all unit tests pass

**Comment by RohansPersonalGit** [comment]
Working on this!

**Comment by ValarDragon** [comment]
Great idea!

**Comment by p0mvn** [comment]
Given how risky changes on IAVL are. I think that this refactor is not worth the effort so I'm going to close this. Please let me know if any concerns
