### ISSUE TITLE
Migration code

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/iavl#4]
IAVL fast node migration code

- [ ] We need to make a migrate function, that reads every 'live node' in the node db, and derives the corresponding fastNode if its a leaf, and sets it. This should be a standalone function which we can test. 
- [ ] Then we should make an automatic way to test if the binary was upgraded. One way to do this is by making an entry in the nodedb at a specific key (perhaps with a `v` prefix), and the value at that key be a version number. If the version doesn't exist, or if its `1`, then  run this migration to get the new data.

**Comment by tac0turtle** [comment]
can this also be treated as upgrade and then the fast cache will populate on its own over time? Not all data will be added but the most touched parts?

**Comment by ValarDragon** [comment]
We can't do that and get fast iteration
